### ISSUE TITLE
sollen wir public/images oder src/assets/images für bilddateien benutzen?

### ISSUE THREAD

**Issue by sanberksoysal** [HaanerBarbaren/tutoring-frontend#1]

**Comment by LaurensHei** [comment]
mir eig egal

**Comment by 3nt3** [comment]
are there any real reasons to use either?

**Comment by 3nt3** [comment]
[hier](https://www.delftstack.com/howto/react/react-img-src/) steht dass man `src/assets` benutzen soll wegen webpack oder so. ich schließe das jetzt einfach mal weil es allen egal ist (außer leonard, jan und jakob, die sich nicht beteiligt haben)
