### ISSUE TITLE
Nicht fucking `table` benutzten ist 2003 oder was

### ISSUE THREAD

**Issue by 3nt3** [HaanerBarbaren/tutoring-frontend#5]
https://github.com/HaanerBarbaren/tutoring-frontend/blob/03522968bd6bb10cff64561c6336f834841403e4/src/pages/RegisterPage.tsx#L169

das sollte man auf jeden fall mit css grid oder flexbox neu machen

**Comment by soysalayberk** [comment]
:(

**Comment by sanberksoysal** [comment]
😥😥

**Comment by soysalayberk** [comment]
ok
